/**
* @Author : Monika Bisht
* @Company : Cognizant
* @description : This class will be used for constant variable.
*/
public class ConstantsUtility
{
  public static final String IS_TRUE = 'true';
  public static final String IS_FALSE = 'false';
  public static final String VIPFLAG_YES = 'Y';
  public static final String VIPFLAG_NO = 'N';
  public static final String VIPFLAG_ERROR = 'E';
    
  public static final String RPABOT_SUCCESS_RESPONSE_MESSAGE = 'Email successfully processed in Salesforce.';
  public static final String RPABOT_CUSTOMSETTING_NAME = 'RPABot';
  public static final String RPABOT_SIZE_EXCEPTION_MESSAGE = 'Email size limit exceeded.';
  public static final String RPABOT_DOCUMENT_ID_SAPERATOR = ',';
  public static final String CASE_ASSIGNMENTRULE = 'Case';
  public static final String EMAIL_TEMPLATE_PRIORITY_CASE = 'KronosRosteringPriorityCaseFeedbackEsclationTemplate';
  public static final String EMAIL_TEMPLATE_FEEDBACK_ESCALATION_CASE = 'KronosRosteringFeedbackEsclationTemplate';
  public static final String CRITICAL_CASE = 'Critical';
  public static final String HIGH_CASE = 'High';
  public static final String STORE_NOMINATION_UNSUCCESSFUL = 'Store Nomination Exception';// Added by Saniya Virmani for 457
  public static final String RECAPTCHA_FAIL = 'reCaptcha verification failed. Please contact to your System Administrator';// Added by Saniya Virmani for 457
}