/**
    * @Author : Sunil
    * @Company : Cognizant
    * @description : This Class is wrapper for NSTWrapper
    */
    public class NSTRequestWrapper{
        @AuraEnabled
        public String title;
        @AuraEnabled
        public String icn;
        @AuraEnabled
        public DateTime dateGroup;
        @AuraEnabled
        public String visittime;
        @AuraEnabled
        public String param1;
        @AuraEnabled
        public String value1;
        @AuraEnabled
        public String param2;
        @AuraEnabled
        public String value2;
        @AuraEnabled
        public String param3;
        @AuraEnabled
        public String value3;
        @AuraEnabled
        public String param4;
        @AuraEnabled
        public String value4;
        @AuraEnabled
        public String param5;
        @AuraEnabled
        public String value5;
        @AuraEnabled
        public String param6;
        @AuraEnabled
        public String value6;
    }